# Generated by go2rpm 1
%bcond_without check

# https://github.com/mozilla-services/pkcs7
%global goipath         go.mozilla.org/pkcs7
%global forgeurl        https://github.com/mozilla-services/pkcs7
%global commit          432b2356ecb18209c1cec25680b8a23632794f21

%gometa

%global godevelheader %{expand:
Requires:               openssl}

%global common_description %{expand:
This package implements a subset of PKCS#7/Cryptographic Message Syntax
(rfc2315, rfc5652).}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        PKCS#7/Cryptographic Message Syntax (rfc2315, rfc5652)

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  openssl

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Oct 01 00:26:01 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.1.20200930git432b235
- Initial package
