# Generated by go2rpm
%bcond_without check

# https://github.com/chmduquesne/rollinghash
%global goipath         github.com/chmduquesne/rollinghash
Version:                4.0.0

%gometa

%global common_description %{expand:
This package contains several various rolling hashes for you to play with crazy
ideas. The API design philosophy is to stick as closely as possible to the
interface provided by the builtin hash package (the hashes implemented here are
effectively drop-in replacements for their builtin counterparts), while
providing simultaneously the highest speed and simplicity.}

%global golicenses      LICENSE.txt
%global godocs          README.md

Name:           %{goname}
Release:        6%{?dist}
Summary:        Implementation of some rolling hashes in Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep
# remove test program; it pulls in extra dependencies
rm -rf roll


%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jan 28 2020 Fedora Release Engineering <releng@fedoraproject.org> - 4.0.0-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 4.0.0-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Fri May 24 13:05:56 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 4.0.0-4
- Update to new macros

* Thu Jan 31 2019 Fedora Release Engineering <releng@fedoraproject.org> - 4.0.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Wed Oct 24 2018 Fabio Valentini <decathorpe@gmail.com> - 4.0.0-2
- Use standard GitHub SourceURL again for consistency between releases.
- Use forgeautosetup instead of gosetup.

* Thu Sep 13 2018 Fabio Valentini <decathorpe@gmail.com> - 4.0.0-1
- Update to version 4.0.0.

* Thu Aug 16 2018 Fabio Valentini <decathorpe@gmail.com> - 3.0.1-5
- Remove test program, it pulls in extra dependencies.

* Thu Aug 16 2018 Fabio Valentini <decathorpe@gmail.com> - 3.0.1-4
- Update to spec 3.0.

* Fri Jul 13 2018 Fedora Release Engineering <releng@fedoraproject.org> - 3.0.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Wed Feb 07 2018 Fedora Release Engineering <releng@fedoraproject.org> - 3.0.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Sat Jan 20 2018 Fabio Valentini <decathorpe@gmail.com> - 3.0.1-1
- Update to version 3.0.1.

* Tue Nov 28 2017 Fabio Valentini <decathorpe@gmail.com> - 3.0.0-1
- Bump to version 3.0.0.

* Thu Nov 23 2017 Fabio Valentini <decathorpe@gmail.com> - 2.0.2-4.20171121.gite6b39c4
- Bump to commit e6b39c4.

* Wed Aug 02 2017 Fedora Release Engineering <releng@fedoraproject.org> - 2.0.2-3.1.git043b8fd
- Rebuilt for https://fedoraproject.org/wiki/Fedora_27_Binutils_Mass_Rebuild

* Wed Jul 26 2017 Fedora Release Engineering <releng@fedoraproject.org> - 2.0.2-2.1.git043b8fd
- Rebuilt for https://fedoraproject.org/wiki/Fedora_27_Mass_Rebuild

* Wed Mar 22 2017 Fabio Valentini <decathorpe@gmail.com> - 2.0.2-1.1.git043b8fd
- Bump to commit 043b8fdecc9816f0011a056f6d92f9a091ab63dd.
- Adapt provides to upstream changes.

* Wed Mar 01 2017 Fabio Valentini <decathorpe@gmail.com> - 2.0.2-0.1.git56b51d0
- First package for Fedora
