# Generated by go2rpm 1
%bcond_without check

# https://github.com/istio/api
%global goipath         istio.io/api
%global forgeurl        https://github.com/istio/api
Version:                1.7.0
%global tag             1.7.0

%gometa

%global common_description %{expand:
API definitions for the Istio project.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md GUIDELINES.md README.md SUPPORT.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        API definitions for the Istio project

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gogo/protobuf/gogoproto)
BuildRequires:  golang(github.com/gogo/protobuf/jsonpb)
BuildRequires:  golang(github.com/gogo/protobuf/proto)
BuildRequires:  golang(github.com/gogo/protobuf/protoc-gen-gogo/descriptor)
BuildRequires:  golang(github.com/gogo/protobuf/sortkeys)
BuildRequires:  golang(github.com/gogo/protobuf/types)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/codes)
BuildRequires:  golang(google.golang.org/grpc/status)
BuildRequires:  golang(istio.io/gogo-genproto/googleapis/google/api)
BuildRequires:  golang(istio.io/gogo-genproto/googleapis/google/rpc)
BuildRequires:  golang(k8s.io/apimachinery/pkg/api/resource)
BuildRequires:  golang(k8s.io/apimachinery/pkg/apis/meta/v1)
BuildRequires:  golang(k8s.io/apimachinery/pkg/util/intstr)

%description
%{common_description}

%gopkg

%prep
%goprep


%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Jul 23 21:35:14 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 1.7.0-1
- Initial package
