# Generated by go2rpm 1
%bcond_without check

# https://github.com/jcmturner/gofork
%global goipath         github.com/jcmturner/gofork
Version:                1.0.0

%gometa

%global common_description %{expand:
Forked and modified Go standard library packages to work around issues.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        3%{?dist}
Summary:        Forked Go standard library packages with work arounds

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sat Aug 01 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.0-3
- Second attempt - Rebuilt for
  https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Thu Feb 20 21:23:05 EST 2020 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 1.0.0-1
- Initial package
