# Generated by go2rpm
%bcond_without check

# https://github.com/circonus-labs/go-apiclient
%global goipath         github.com/circonus-labs/go-apiclient
Version:                0.6.1

%gometa

%global common_description %{expand:
Package Apiclient provides methods for interacting with the Circonus API. See
the full Circonus API Documentation at https://login.circonus.com/resources/api
for more information. }

%global golicenses      LICENSE
%global godocs          CHANGELOG.md README.md examples

Name:           %{goname}
Release:        3%{?dist}
Summary:        Circonus api client

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/hashicorp/go-retryablehttp)
BuildRequires:  golang(github.com/pkg/errors)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%gopkgfiles

%changelog
* Tue Jan 28 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.6.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.6.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Wed Apr 17 16:19:59 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.6.1-1
- Initial package
