# Generated by go2rpm
# https://github.com/go-xorm/xorm/issues/1343
%ifnarch %{ix86} %{arm}
%bcond_without check
%endif

# https://github.com/go-xorm/xorm
%global goipath         github.com/go-xorm/xorm
Version:                0.7.6

%gometa

%global common_description %{expand:
Xorm is a simple and powerful ORM for Go.}

%global golicenses      LICENSE
%global godocs          docs examples CONTRIBUTING.md\\\
                        README.md README_CN.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Simple and Powerful ORM for Go

# Upstream license specification: BSD-3-Clause
License:        BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/go-sql-driver/mysql)
BuildRequires:  golang(github.com/lib/pq)
BuildRequires:  golang(github.com/mattn/go-sqlite3)
BuildRequires:  golang(xorm.io/builder)
BuildRequires:  golang(xorm.io/core)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/denisenkom/go-mssqldb)
BuildRequires:  golang(github.com/jackc/pgx/stdlib)
BuildRequires:  golang(github.com/stretchr/testify/assert)
BuildRequires:  golang(github.com/ziutek/mymysql/godrv)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.7.6-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Aug 29 19:08:42 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.7.6-1
- Release 0.7.6

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.7.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Fri May 31 17:45:48 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.7.1-2
- Update to new macros

* Mon Mar 18 2019 Nathan Scott <nathans@redhat.com> - 0.7.1-1
- First package for Fedora
