# Generated by go2rpm
%bcond_without check

# https://github.com/yuin/gopher-lua
%global goipath         github.com/yuin/gopher-lua
%global commit          1cd887cd7036fd4be7a0cb180dd508cb8e2e689a

%gometa

%global common_description %{expand:
GopherLua is a Lua5.1 VM and compiler written in Go. GopherLua has a same goal
with Lua: Be a scripting language with extensible semantics . It provides Go
APIs that allow you to easily embed a scripting language to your Go host
programs.}

%global golicenses      LICENSE
%global godocs          README.rst

Name:           %{goname}
Version:        0
Release:        0.11%{?dist}
Summary:        VM and compiler for Lua in Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/chzyer/readline)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.rst _lua5.1-tests/README
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.11
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.10
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Thu May 30 15:05:22 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.9.20190530git1cd887c
- Bump to commit 1cd887cd7036fd4be7a0cb180dd508cb8e2e689a

* Fri Feb 01 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.8.gitca850f5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Tue Oct 23 2018 Nicolas Mailhot <nim@fedoraproject.org> - 0-0.7.gitca850f5
- redhat-rpm-config-123 triggers bugs in gosetup, remove it from Go spec files as it’s just an alias
- https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/RWD5YATAYAFWKIDZBB7EB6N5DAO4ZKFM/

* Fri Jul 13 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.6.gitca850f5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Thu Jun 28 2018 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.5.20180628gitca850f5
- Bump to commit ca850f594eaafa5468da2bd53b865e4ee55be18b

* Fri Mar 09 2018 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.4.20180314git7d7bc87
- Update with the new Go packaging
- Upstream GIT revision 7d7bc87

* Wed Feb 07 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.3.20171031git609c9cd
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Thu Dec 07 2017 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.2.20171031git609c9cd
- Upstream GIT revision 609c9cd

* Fri Sep 29 2017 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.1.20170915giteb1c729
- First package for Fedora
