# Generated by go2rpm 1
%bcond_without check

# https://github.com/vcabbage/amqp
%global goipath         pack.ag/amqp
%global forgeurl        https://github.com/vcabbage/amqp
Version:                0.12.0

%gometa

%global common_description %{expand:
AMQP 1.0 client library for Go.}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        AMQP 1.0 client library for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/google/go-cmp/cmp/cmpopts)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.12.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Tue Aug 20 20:58:48 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.12.0-1
- Initial package
