# Generated by go2rpm
%bcond_without check

# https://github.com/influxdata/influxdb1-client
%global goipath         github.com/influxdata/influxdb1-client
%global commit          02f0bf5dbca364fe200ee3f5709c8cc0c9bda0d0

%gometa

%global common_description %{expand:
Influxdb1-clientv2 is the current Go client API for InfluxDB 1.x.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.5%{?dist}
Summary:        Old clientv2 for InfluxDB 1.x

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Jul 28 00:19:01 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.5.20200728git02f0bf5
- Bump to commit 02f0bf5dbca364fe200ee3f5709c8cc0c9bda0d0

* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Wed May 15 02:06:43 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.1.20190626git8ff2fc3
- Initial package
