# Generated by go2rpm
%bcond_without check

# https://github.com/go-macaron/inject
%global goipath         github.com/go-macaron/inject
%global commit          d8a0b8677191f4380287cfebd08e462217bac7ad

%gometa

# Remove in F33:
%global godevelheader %{expand:
Obsoletes:      golang-github-go-macaron-inject-devel < 0-0.7
Obsoletes:      golang-github-go-macaron-inject-unit-test-devel < 0-0.7
}

%global common_description %{expand:
Package Inject provides utilities for mapping and injecting dependencies in
various ways.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.10%{?dist}
Summary:        Utilities for mapping and injecting dependencies in various ways

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.10
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.9
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Tue Jul 09 2019 Elliott Sales de Andrade <quantum.analyst@gmail.com> - 0-0.8.20190703gitd8a0b86
- Add Obsoletes for old names

* Mon May 27 18:38:58 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.7.20190703gitd8a0b86
- Update to new macros

* Fri Feb 01 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.6.20160627gitd8a0b86
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Fri Jul 13 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.5.20160627gitd8a0b86
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Wed Feb 07 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.4.20160627gitd8a0b86
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Wed Aug 02 2017 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.3.20160627gitd8a0b86
- Rebuilt for https://fedoraproject.org/wiki/Fedora_27_Binutils_Mass_Rebuild

* Wed Jul 26 2017 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.2.20160627gitd8a0b86
- Rebuilt for https://fedoraproject.org/wiki/Fedora_27_Mass_Rebuild

* Fri May 05 2017 Matthias Runge <mrunge@redhat.com> - 0-0.1.20160627gitd8a0b86
- First package for Fedora
