# Generated by go2rpm 1
%bcond_without check

# https://github.com/gobuffalo/packr
%global goipath         github.com/gobuffalo/packr
Version:                2.6.0

%gometa

%global goipaths0       github.com/gobuffalo/packr
%global goipathsex0     github.com/gobuffalo/packr/v2
%global goipaths1       github.com/gobuffalo/packr/v2

%global common_description %{expand:
Packr is a simple solution for bundling static assets inside of Go binaries.
Most importantly it does it in a way that is friendly to developers while they
are developing.}

%global golicenses      LICENSE.txt
%global godocs          example README.md SHOULDERS.md

Name:           %{goname}
Release:        2%{?dist}
Summary:        Simple and easy way to embed static files into Go binaries

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/gobuffalo/envy)
BuildRequires:  golang(github.com/gobuffalo/logger)
BuildRequires:  golang(github.com/gobuffalo/packd)
BuildRequires:  golang(github.com/karrick/godirwalk)
BuildRequires:  golang(github.com/rogpeppe/go-internal/modfile)
BuildRequires:  golang(github.com/sirupsen/logrus)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(golang.org/x/sync/errgroup)
BuildRequires:  golang(golang.org/x/tools/go/ast/astutil)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 2.6.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Wed Aug 21 11:48:02 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 2.6.0-1
- Initial package
