# Generated by go2rpm 1
%bcond_without check

# https://github.com/mattetti/filebuffer
%global goipath         github.com/mattetti/filebuffer
Version:                1.0.0
%global tag             v1.0.0

%gometa

%global common_description %{expand:
Filebuffer is a package implementing a few file-like interfaces. The
implementation is backed by a byte buffer. The main purpose is to have in-
memory file alternative.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Filebuffer provides file-like interfaces, backed by an in-memory byte buffer

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Feb 12 2020 Mark Goodwin <mgoodwin@redhat.com> - 1.0.0-1
- Initial package
