# Generated by go2rpm
%bcond_without check

# https://github.com/influxdata/line-protocol
%global goipath         github.com/influxdata/line-protocol
%global commit          a3afd890113fb9f0337e05808bb06fb0ca4c685a

%gometa

%global common_description %{expand:
This is an encoder for the influx line protocol.

It has an interface similar to the standard library's json.Encoder.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.3%{?dist}
Summary:        Encoder for the influx line protocol

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Thu Apr 25 00:19:21 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.1.20190623gita3afd89
- Initial package
