# Generated by go2rpm 1
%bcond_without check

# https://github.com/aalpar/deheap
%global goipath         github.com/aalpar/deheap
%global commit          9a0c2883bd56c7fda899cf7b4b3eca4f353e0c56

%gometa

%global common_description %{expand:
Doubly ended heap.}

%global golicenses      LICENSE.txt
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.2%{?dist}
Summary:        Doubly ended heap

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Sat Jun 20 13:25:09 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.1.20200702git9a0c288
- Initial package
