# Generated by go2rpm
%ifnarch s390x
%bcond_without check
%endif

# https://github.com/gin-gonic/gin
%global goipath         github.com/gin-gonic/gin
Version:                1.3.0

%gometa

%global common_description %{expand:
Gin is a web framework written in Go. It features a martini-like API with much
better performance, up to 40 times faster thanks to httprouter. If you need
performance and good productivity, you will love Gin.}

%global golicenses      LICENSE
%global godocs          examples AUTHORS.md BENCHMARKS.md CHANGELOG.md\\\
                        CODE_OF_CONDUCT.md CONTRIBUTING.md README.md

Name:           %{goname}
Release:        3%{?dist}
Summary:        HTTP web framework written in Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/dustin/go-broadcast)
BuildRequires:  golang(github.com/gin-contrib/sse)
BuildRequires:  golang(github.com/gin-gonic/autotls)
BuildRequires:  golang(github.com/golang/protobuf/proto)
BuildRequires:  golang(github.com/jessevdk/go-assets)
BuildRequires:  golang(github.com/manucorporat/stats)
BuildRequires:  golang(github.com/mattn/go-isatty)
# Cyclic. Only in examples
# BuildRequires:  golang(github.com/thinkerou/favicon)
BuildRequires:  golang(github.com/ugorji/go/codec)
BuildRequires:  golang(golang.org/x/crypto/acme/autocert)
BuildRequires:  golang(golang.org/x/net/context)
BuildRequires:  golang(golang.org/x/sync/errgroup)
BuildRequires:  golang(google.golang.org/grpc)
BuildRequires:  golang(google.golang.org/grpc/reflection)
BuildRequires:  golang(gopkg.in/go-playground/validator.v8)
BuildRequires:  golang(gopkg.in/yaml.v2)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/stretchr/testify/assert)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.3.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.3.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Tue Apr 30 14:45:15 CEST 2019 Robert-André Mauchin <zebob.m@gmail.com> - 1.3.0-1
- Initial package
