# Generated by go2rpm 1
%bcond_without check

# https://github.com/tomnomnom/rawhttp
%global goipath         github.com/tomnomnom/rawhttp
%global commit          e904eb0f15db2e4db2528242d0992d95330c94a7

%gometa

%global common_description %{expand:
A Go library for making HTTP requests with complete control.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           %{goname}
Version:        0
Release:        0.2%{?dist}
Summary:        Making HTTP requests with complete control

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Mon Jul 27 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Wed May 27 2020 Fabian Affolter <mail@fabian-affolter.ch> - 0-0.1.20200527gite904eb0
- Add license details

* Mon May 25 2020 Fabian Affolter <mail@fabian-affolter.ch> - 0-0.1.20200525gitf7ac0ba
- Initial package

