# Generated by go2rpm 1
%bcond_without check

# https://github.com/apparentlymart/go-textseg
%global goipath         github.com/apparentlymart/go-textseg/v12
Version:                12.0.0

%gometa

%global common_description %{expand:
Go implementation of Unicode Text Segmentation.}

%global golicenses      LICENSE

Name:           %{goname}
Release:        2%{?dist}
Summary:        Go implementation of Unicode Text Segmentation

License:        MIT and ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Tue Sep 08 17:49:44 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 12.0.0-2
- Fix archive upload

* Thu Jul 23 09:53:53 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 12.0.0-1
- Initial package
