# Generated by go2rpm 1
%bcond_without check

%global golang_arches x86_64 aarch64 ppc64le s390x

# https://github.com/cockroachdb/pebble
%global goipath         github.com/cockroachdb/pebble
%global commit          069f1e1b4e47dcfb81e1ac38bf98f1fd1877b2bb

%gometa

%global common_description %{expand:
RocksDB/LevelDB inspired key-value database in Go.}

%global golicenses      LICENSE
%global godocs          docs README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        RocksDB/LevelDB inspired key-value database in Go

# Upstream license specification: MIT and Apache-2.0 and BSD-3-Clause
License:        MIT and ASL 2.0 and BSD
URL:            %{gourl}
Source0:        %{gosource}



BuildRequires:  golang(github.com/cockroachdb/errors)
BuildRequires:  golang(github.com/cockroachdb/redact)
BuildRequires:  golang(github.com/codahale/hdrhistogram)
BuildRequires:  golang(github.com/golang/snappy)
BuildRequires:  golang(github.com/spf13/cobra)
BuildRequires:  golang(golang.org/x/exp/rand)
BuildRequires:  golang(golang.org/x/sys/unix)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/ghemawat/stream)
BuildRequires:  golang(github.com/kr/pretty)
BuildRequires:  golang(github.com/pmezard/go-difflib/difflib)
BuildRequires:  golang(github.com/stretchr/testify/require)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep
sed -i 's|\[JOB 5\] WAL delete error: ‹×›|\[JOB 5\] WAL delete error: unredacted error: ‹×›|' event_listener_test.go

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck -d internal/lint -d internal/manifest
%endif

%files
%license LICENSE
%doc docs README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Sep 09 00:46:48 CEST 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.1.20200908git069f1e1
- Initial package
