# Generated by go2rpm 1
%bcond_without check

# https://github.com/grafov/hulk
%global goipath         github.com/grafov/hulk
%global commit          96706999f6b1dda6598f1365de7f104658cc8c25

%gometa

%global common_description %{expand:
HULK is a web server denial of service tool. It is designed to generate \
volumes of unique and obfuscated traffic at a web server, bypassing caching \
engines and therefore hitting the server's direct resource pool.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           hulk
Version:        0
Release:        0.2%{?dist}
Summary:        DoS tool using unique and obfuscated traffic

License:        GPLv3
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/hulk %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md docker/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Tue Jul 28 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Fri Mar 27 2020 Fabian Affolter <mail@fabian-affolter.ch> - 0-0.1.20200330git9670699
- Initial package for Fedora

