%{?nodejs_find_provides_and_requires}

%global packagename braces

# Tests disabled temporarily because npm(snapdragon) is too new
%global enable_tests 0

Name:		nodejs-braces
Version:	2.3.2
Release:	5%{?dist}
Summary:	Fastest brace expansion for node.js

License:	MIT
URL:		https://github.com/micromatch/braces
Source0:	https://registry.npmjs.org/%{packagename}/-/%{packagename}-%{version}.tgz
# The test files are not included in the npm tarball.
# Source1 is generated by running Source10, which pulls from the upstream
# version control repository.
Source1:	tests-%{version}.tar.bz2
Source2:	examples-%{version}.tar.bz2
Source10:	dl-tests.sh


BuildArch:	noarch
%if 0%{?fedora} >= 19
ExclusiveArch: %{nodejs_arches} noarch
%else
ExclusiveArch: %{ix86} x86_64 %{arm} noarch
%endif

BuildRequires:	nodejs-packaging
BuildRequires:	npm(array-unique)
BuildRequires:	npm(arr-flatten)
BuildRequires:	npm(define-property)
BuildRequires:	npm(extend-shallow)
BuildRequires:	npm(fill-range)
BuildRequires:	npm(isobject)
BuildRequires:	npm(repeat-element)
BuildRequires:	npm(snapdragon)
BuildRequires:	npm(split-string)
BuildRequires:	npm(to-regex)
%if 0%{?enable_tests}
BuildRequires:	mocha
BuildRequires:	npm(ansi-cyan)
#BuildRequires:	npm(benchmarked)
BuildRequires:	npm(brace-expansion)
BuildRequires:	npm(cross-spawn)
BuildRequires:	npm(fs-exists-sync)
BuildRequires:	npm(is-windows)
BuildRequires:	npm(minimatch)
BuildRequires:	npm(noncharacters)
BuildRequires:	npm(pretty-bytes)
BuildRequires:	npm(text-table)
BuildRequires:	npm(time-diff)
BuildRequires:	npm(yargs-parser)
%endif

%description
Fastest brace expansion for node.js, with the most complete support for the
Bash 4.3 braces specification.


%prep
%setup -q -n package
# setup the tests
%setup -q -T -D -a 1 -n package
# setup the examples
%setup -q -T -D -a 2 -n package

%nodejs_fixdep snapdragon
%nodejs_fixdep snapdragon-node
%nodejs_fixdep split-string

%build
# nothing to do!

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/%{packagename}
cp -pr package.json *.js lib/ \
	%{buildroot}%{nodejs_sitelib}/%{packagename}

%nodejs_symlink_deps

%check
%nodejs_symlink_deps --check
%{__nodejs} -e 'require("./")'
%if 0%{?enable_tests}
#npm install --dry-run
%{_bindir}/mocha -R spec
%else
%{_bindir}/echo -e "\e[101m -=#=- Tests disabled -=#=- \e[0m"
%endif


%files
%{!?_licensedir:%global license %doc}
%doc *.md examples/
%license LICENSE
%{nodejs_sitelib}/%{packagename}


%changelog
* Wed Jan 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 2.3.2-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Thu Jul 25 2019 Fedora Release Engineering <releng@fedoraproject.org> - 2.3.2-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Fri Feb 01 2019 Fedora Release Engineering <releng@fedoraproject.org> - 2.3.2-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Fri Jul 13 2018 Fedora Release Engineering <releng@fedoraproject.org> - 2.3.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Wed Apr 18 2018 Jared K. Smith <jsmith@fedoraproject.org> - 2.3.2-1
- Update to upstream 2.3.2 release

* Thu Feb 08 2018 Fedora Release Engineering <releng@fedoraproject.org> - 2.2.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Fri Aug 18 2017 Jared Smith <jsmith@fedoraproject.org> - 2.2.2-1
- Update to upstream 2.2.2 release

* Fri Apr 14 2017 Jared Smith <jsmith@fedoraproject.org> - 2.0.4-1
- Update to upstream 2.0.4 release

* Sat Jun 18 2016 Jared Smith <jsmith@fedoraproject.org> - 1.8.5-1
- Update to upstream 1.8.5 release

* Thu Feb  4 2016 Jared Smith <jsmith@fedoraproject.org> - 1.8.3-1
- Initial packaging
