Name:           perl-String-TtyLength
Version:        0.02
Release:        1%{?dist}
Summary:        Length or width of string excluding ANSI tty codes
License:        GPL+ or Artistic
URL:            https://metacpan.org/pod/String::TtyLength
Source0:        https://cpan.metacpan.org/authors/id/N/NE/NEILB/String-TtyLength-%{version}.tar.gz
BuildArch:      noarch
# build requirements
BuildRequires:  make
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.76
# runtime requirements
BuildRequires:  perl(Exporter)
BuildRequires:  perl(parent)
BuildRequires:  perl(strict)
BuildRequires:  perl(Unicode::EastAsianWidth) >= 12.0
BuildRequires:  perl(warnings)
# test requirements
BuildRequires:  perl(Test2::V0)
BuildRequires:  perl(utf8)
Requires:       perl(:MODULE_COMPAT_%(eval "`/usr/bin/perl -V:version`"; echo $version))

%{?perl_default_filter}

%description
This module provides two functions which tell you the length and width
of a string as it will appear on a terminal (tty), excluding any ANSI
escape codes.

%prep
%setup -q -n String-TtyLength-%{version}

%build
/usr/bin/perl Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1 NO_PERLLOCAL=1
%{make_build}

%install
%{make_install}
%{_fixperms} $RPM_BUILD_ROOT/*

%check
%{make_build} test

%files
%doc Changes README
%license LICENSE
%{perl_vendorlib}/String*
%{_mandir}/man3/String*

%changelog
* Sun Sep 13 2020 Emmanuel Seyman <emmanuel@seyman.fr> - 0.02-1
- Initial specfile, based on the one autogenerated by cpanspec 1.78.
