Name:           perl-Mojolicious-Plugin-OpenAPI
Version:        3.33
Release:        2%{?dist}
Summary:        OpenAPI / Swagger plugin for Mojolicious
# MIT-licensed files: t/spec/v2-petstore.json, t/v3-basic.t, t/v3-nullable.t, t/v3-style-array.t
# ASL 2.0-licensed files: t/spec/bundlecheck.json.
License:        Artistic 2.0

URL:            https://metacpan.org/release/Mojolicious-Plugin-OpenAPI
Source0:        https://cpan.metacpan.org/authors/id/J/JH/JHTHORSEN/Mojolicious-Plugin-OpenAPI-%{version}.tar.gz

BuildArch:      noarch
# build requirements
BuildRequires:  make
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.76
BuildRequires:  perl(utf8)
# runtime requirements
BuildRequires:  perl(Carp)
BuildRequires:  perl(JSON::Validator) >= 3.16
BuildRequires:  perl(JSON::Validator::Ref)
BuildRequires:  perl(Mojo::Base)
BuildRequires:  perl(Mojo::JSON)
BuildRequires:  perl(Mojo::Util)
BuildRequires:  perl(Mojolicious::Plugin)
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(Time::Local)
BuildRequires:  perl(constant)
# test requirements
BuildRequires:  perl(Data::Validate::IP)
BuildRequires:  perl(File::Find)
BuildRequires:  perl(Mojo::File)
BuildRequires:  perl(Mojolicious) >= 8.00
BuildRequires:  perl(Mojolicious::Controller)
BuildRequires:  perl(Mojolicious::Lite)
BuildRequires:  perl(Test::Mojo)
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(Text::Markdown)
BuildRequires:  perl(lib)
Requires:       perl(:MODULE_COMPAT_%(eval "`/usr/bin/perl -V:version`"; echo $version))
Requires:       perl(JSON::Validator) >= 4.00
Requires:       perl(Mojolicious::Plugin)
Recommends:     perl(Config)
Suggests:       perl(Text::Markdown)

%{?perl_default_filter}

## Filter unneeded Requires with RPM
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^perl\\(JSON::Validator\\)$

%description
Mojolicious::Plugin::OpenAPI is a Mojolicious::Plugin that add routes and
input/output validation to your Mojolicious application based on a OpenAPI
(Swagger) specification. This plugin supports both version 2.0 and 3.x,
though 3.x might have some missing features.

%prep
%setup -q -n Mojolicious-Plugin-OpenAPI-%{version}

%build
/usr/bin/perl Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1 NO_PERLLOCAL=1
%{make_build}

%install
%{make_install}
%{_fixperms} $RPM_BUILD_ROOT/*

%check
DUMMY_DB_ERROR= JSON_VALIDATOR_DEBUG= MOJO_OPENAPI_DEBUG= %{make_build} test

%files
%doc Changes README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jun 23 2020 Jitka Plesnikova <jplesnik@redhat.com> - 3.33-2
- Perl 5.32 rebuild

* Sun Jun 14 2020 Emmanuel Seyman <emmanuel@seyman.fr> - 3.33-1
- Update to 3.33

* Thu Apr 09 2020 Emmanuel Seyman <emmanuel@seyman.fr> - 3.31-2
- Take into account more review feedback (#1818936)

* Wed Apr 08 2020 Emmanuel Seyman <emmanuel@seyman.fr> - 3.31-1
- Update to 3.31
- Take into account review feedback (#1818936)

* Mon Mar 30 2020 Emmanuel Seyman <emmanuel@seyman.fr> - 3.30-1
- Initial specfile, based on the one autogenerated by cpanspec 1.78.
