Name:           perl-Data-IEEE754
Version:        0.02
Release:        1%{?dist}
Summary:        Pack and unpack big-endian IEEE 754 floats and doubles
License:        Artistic 2.0
URL:            https://metacpan.org/release/Data-IEEE754/
Source0:        https://cpan.metacpan.org/authors/id/M/MA/MAXMIND/Data-IEEE754-%{version}.tar.gz
BuildArch:      noarch
BuildRequires:  coreutils
BuildRequires:  make
BuildRequires:  perl-generators
BuildRequires:  perl-interpreter
BuildRequires:  perl(ExtUtils::MakeMaker) >= 6.76
BuildRequires:  perl(strict)
BuildRequires:  perl(warnings)
# Run-time:
BuildRequires:  perl(Config)
BuildRequires:  perl(Exporter)
BuildRequires:  perl(utf8)
# Tests:
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(Test::Bits)
BuildRequires:  perl(Test::More) >= 0.96
# Optional tests:
# CPAN::Meta not helful
# CPAN::Meta::Prereqs not helpful
Requires:       perl(:MODULE_COMPAT_%(eval "`perl -V:version`"; echo $version))

%description
This Perl module provides some simple convenience functions for packing and
unpacking IEEE 754 floats and doubles. If you can require Perl 5.10 or greater
then this module is pointless. Just use the "d>" and "f>" pack formats
instead.

%prep
%setup -q -n Data-IEEE754-%{version}

%build
perl Makefile.PL INSTALLDIRS=vendor NO_PACKLIST=1 NO_PERLLOCAL=1
%{make_build}

%install
%{make_install}
%{_fixperms} $RPM_BUILD_ROOT/*

%check
unset AUTHOR_TESTING
make test

%files
%license LICENSE
%doc Changes CONTRIBUTING.md README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Mon Aug 10 2020 Petr Pisar <ppisar@redhat.com> 0.02-1
- Specfile autogenerated by cpanspec 1.78.
