# Generated by rust2rpm 10
%bcond_without check
%global debug_package %{nil}

%global crate slog

Name:           rust-%{crate}
Version:        2.5.2
Release:        2%{?dist}
Summary:        Structured, extensible, composable logging for Rust

# Upstream license specification: MPL-2.0 OR MIT OR Apache-2.0
License:        MPLv2.0 or MIT or ASL 2.0
URL:            https://crates.io/crates/slog
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Structured, extensible, composable logging for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MPL2 LICENSE-MIT LICENSE-APACHE
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+dynamic-keys-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dynamic-keys-devel %{_description}

This package contains library source intended for building other packages
which use "dynamic-keys" feature of "%{crate}" crate.

%files       -n %{name}+dynamic-keys-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+erased-serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+erased-serde-devel %{_description}

This package contains library source intended for building other packages
which use "erased-serde" feature of "%{crate}" crate.

%files       -n %{name}+erased-serde-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+max_level_debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_debug-devel %{_description}

This package contains library source intended for building other packages
which use "max_level_debug" feature of "%{crate}" crate.

%files       -n %{name}+max_level_debug-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+max_level_error-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_error-devel %{_description}

This package contains library source intended for building other packages
which use "max_level_error" feature of "%{crate}" crate.

%files       -n %{name}+max_level_error-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+max_level_info-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_info-devel %{_description}

This package contains library source intended for building other packages
which use "max_level_info" feature of "%{crate}" crate.

%files       -n %{name}+max_level_info-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+max_level_off-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_off-devel %{_description}

This package contains library source intended for building other packages
which use "max_level_off" feature of "%{crate}" crate.

%files       -n %{name}+max_level_off-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+max_level_trace-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_trace-devel %{_description}

This package contains library source intended for building other packages
which use "max_level_trace" feature of "%{crate}" crate.

%files       -n %{name}+max_level_trace-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+max_level_warn-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+max_level_warn-devel %{_description}

This package contains library source intended for building other packages
which use "max_level_warn" feature of "%{crate}" crate.

%files       -n %{name}+max_level_warn-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+nested-values-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nested-values-devel %{_description}

This package contains library source intended for building other packages
which use "nested-values" feature of "%{crate}" crate.

%files       -n %{name}+nested-values-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+nothreads-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nothreads-devel %{_description}

This package contains library source intended for building other packages
which use "nothreads" feature of "%{crate}" crate.

%files       -n %{name}+nothreads-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+release_max_level_debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_debug-devel %{_description}

This package contains library source intended for building other packages
which use "release_max_level_debug" feature of "%{crate}" crate.

%files       -n %{name}+release_max_level_debug-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+release_max_level_error-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_error-devel %{_description}

This package contains library source intended for building other packages
which use "release_max_level_error" feature of "%{crate}" crate.

%files       -n %{name}+release_max_level_error-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+release_max_level_info-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_info-devel %{_description}

This package contains library source intended for building other packages
which use "release_max_level_info" feature of "%{crate}" crate.

%files       -n %{name}+release_max_level_info-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+release_max_level_off-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_off-devel %{_description}

This package contains library source intended for building other packages
which use "release_max_level_off" feature of "%{crate}" crate.

%files       -n %{name}+release_max_level_off-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+release_max_level_trace-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_trace-devel %{_description}

This package contains library source intended for building other packages
which use "release_max_level_trace" feature of "%{crate}" crate.

%files       -n %{name}+release_max_level_trace-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+release_max_level_warn-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+release_max_level_warn-devel %{_description}

This package contains library source intended for building other packages
which use "release_max_level_warn" feature of "%{crate}" crate.

%files       -n %{name}+release_max_level_warn-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages
which use "std" feature of "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 2.5.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Sat Aug 03 14:12:03 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.5.2-1
- Update to 2.5.2

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 2.4.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sat Jun 22 10:14:16 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.4.1-2
- Regenerate

* Wed Mar 13 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 2.4.1-1
- Initial package
