# Generated by rust2rpm 13
%bcond_without check
%global debug_package %{nil}

%global crate smart-default

Name:           rust-%{crate}
Version:        0.6.0
Release:        1%{?dist}
Summary:        Rust custom-derive macro for Default with more control on the fields

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/smart-default
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Rust custom-derive macro for Default with more control on the fields.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Feb 21 22:02:59 EET 2020 Artem Polishchuk <ego.cordatus@gmail.com> - 0.6.0-1
- Initial package
