# Generated by rust2rpm 13
%bcond_without check
%global debug_package %{nil}

%global crate signal-hook

Name:           rust-%{crate}
Version:        0.1.16
Release:        1%{?dist}
Summary:        Unix signal handling

# Upstream license specification: Apache-2.0/MIT
License:        ASL 2.0 or MIT
URL:            https://crates.io/crates/signal-hook
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Unix signal handling.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+futures-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-devel %{_description}

This package contains library source intended for building other packages
which use "futures" feature of "%{crate}" crate.

%files       -n %{name}+futures-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+mio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mio-devel %{_description}

This package contains library source intended for building other packages
which use "mio" feature of "%{crate}" crate.

%files       -n %{name}+mio-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+mio-0_7-support-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mio-0_7-support-devel %{_description}

This package contains library source intended for building other packages
which use "mio-0_7-support" feature of "%{crate}" crate.

%files       -n %{name}+mio-0_7-support-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+mio-support-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mio-support-devel %{_description}

This package contains library source intended for building other packages
which use "mio-support" feature of "%{crate}" crate.

%files       -n %{name}+mio-support-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+mio_0_7-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mio_0_7-devel %{_description}

This package contains library source intended for building other packages
which use "mio_0_7" feature of "%{crate}" crate.

%files       -n %{name}+mio_0_7-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+tokio-reactor-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-reactor-devel %{_description}

This package contains library source intended for building other packages
which use "tokio-reactor" feature of "%{crate}" crate.

%files       -n %{name}+tokio-reactor-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+tokio-support-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-support-devel %{_description}

This package contains library source intended for building other packages
which use "tokio-support" feature of "%{crate}" crate.

%files       -n %{name}+tokio-support-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Jun 19 2020 Josh Stone <jistone@redhat.com> - 0.1.16-1
- Update to 0.1.16

* Mon May 11 2020 Josh Stone <jistone@redhat.com> - 0.1.15-1
- Update to 0.1.15

* Tue May 05 2020 Josh Stone <jistone@redhat.com> - 0.1.14-1
- Update to 0.1.14

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.13-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Mon Jan 27 2020 Josh Stone <jistone@redhat.com> - 0.1.13-1
- Update to 0.1.13

* Thu Nov 28 15:15:09 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.12-1
- Update to 0.1.12

* Tue Nov 19 2019 Josh Stone <jistone@redhat.com> - 0.1.11-1
- Update to 0.1.11

* Sun Sep 08 09:10:52 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.10-1
- Update to 0.1.10

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.9-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sat Jun 22 23:16:52 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.9-2
- Regenerate

* Sun Apr 28 20:37:32 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.9-1
- Update to 0.1.9

* Sun Mar 10 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.8-2
- Do not pull optional dependencies

* Tue Feb 26 2019 Josh Stone <jistone@redhat.com> - 0.1.8-1
- Update to 0.1.8

* Sat Feb 09 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.1.7-3
- Run tests in infrastructure

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.7-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Tue Jan 08 2019 Josh Stone <jistone@redhat.com> - 0.1.7-1
- Update to 0.1.7

* Thu Nov 15 2018 Josh Stone <jistone@redhat.com> - 0.1.6-1
- Initial package
