# Generated by rust2rpm 15
%bcond_without check
%global debug_package %{nil}

%global crate cpuid-bool

Name:           rust-%{crate}
Version:        0.1.2
Release:        2%{?dist}
Summary:        Lightweight no-std compatible alternative to is_x86_feature_detected

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/cpuid-bool
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Lightweight no-std compatible alternative to is_x86_feature_detected.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-MIT LICENSE-APACHE
%doc CHANGELOG.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

# This package only makes sense on x86, but it's still shipped everywhere as a noarch.
# Dependents will get a `compile_error!` if they do try to use this on other targets.
%ifarch %{ix86} x86_64
%build
%cargo_build
%endif

%install
%cargo_install

# This package only makes sense on x86, but it's still shipped everywhere as a noarch.
# Dependents will get a `compile_error!` if they do try to use this on other targets.
%ifarch %{ix86} x86_64
%if %{with check}
%check
%cargo_test
%endif
%endif

%changelog
* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Mon Jul 20 17:23:53 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.1.2-1
- Update to 0.1.2

* Mon Jul 20 10:17:15 CEST 2020 Igor Raits <i.gnatenko.brain@gmail.com> - 0.1.1-1
- Initial package
