# Generated by rust2rpm 13
%bcond_without check
%global debug_package %{nil}

%global crate pipe

Name:           rust-%{crate}
Version:        0.3.0
Release:        2%{?dist}
Summary:        Synchronous Read/Write memory pipe

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/pipe
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Synchronous Read/Write memory pipe.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%license COPYING
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+bidirectional-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bidirectional-devel %{_description}

This package contains library source intended for building other packages
which use "bidirectional" feature of "%{crate}" crate.

%files       -n %{name}+bidirectional-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+readwrite-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+readwrite-devel %{_description}

This package contains library source intended for building other packages
which use "readwrite" feature of "%{crate}" crate.

%files       -n %{name}+readwrite-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+unstable-doc-cfg-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-doc-cfg-devel %{_description}

This package contains library source intended for building other packages
which use "unstable-doc-cfg" feature of "%{crate}" crate.

%files       -n %{name}+unstable-doc-cfg-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Mon May 11 2020 Robert Fairley <rfairley@redhat.com> - 0.3.0-2
- Remove pipe-fix-metadata.diff from git repo
- Fix dates in changelog

* Mon May 11 2020 Robert Fairley <rfairley@redhat.com> - 0.3.0-1
- Update to 0.3.0

* Fri May 01 01:40:30 UTC 2020 Robert Fairley <rfairley@redhat.com> - 0.2.0-1
- Initial package
