# Generated by rust2rpm 15
%bcond_without check
%global debug_package %{nil}

%global crate wayland-scanner

Name:           rust-%{crate}
Version:        0.26.6
Release:        2%{?dist}
Summary:        Wayland Scanner for generating rust APIs from XML wayland protocol files

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/wayland-scanner
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Wayland Scanner for generating rust APIs from XML wayland protocol files.
Intended for use with wayland-sys. You should only need this crate if you are
working on custom wayland protocol extensions. Look at the crate wayland-client
for usable bindings.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch
# Makes code nicer :)
Suggests:       rustfmt

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE.txt
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Jun 14 09:34:56 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.26.6-2
- Include license and readme

* Thu Jun 04 2020 Michel Alexandre Salim <michel@michel-slm.name> - 0.26.6-1
- Update to 0.26.6

* Fri May 22 14:42:00 PDT 2020 Michel Alexandre Salim <salimma@fedoraproject.org> - 0.26.5-1
- Initial package
