# Generated by rust2rpm 13
# * chashmap, cht and contrie are not packaged
%bcond_with check
%global debug_package %{nil}

%global crate dashmap

Name:           rust-%{crate}
Version:        3.11.4
Release:        1%{?dist}
Summary:        Blazing fast concurrent HashMap for Rust

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/dashmap
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Blazing fast concurrent HashMap for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+hashbrown-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hashbrown-devel %{_description}

This package contains library source intended for building other packages
which use "hashbrown" feature of "%{crate}" crate.

%files       -n %{name}+hashbrown-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+no_std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+no_std-devel %{_description}

This package contains library source intended for building other packages
which use "no_std" feature of "%{crate}" crate.

%files       -n %{name}+no_std-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+raw-api-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+raw-api-devel %{_description}

This package contains library source intended for building other packages
which use "raw-api" feature of "%{crate}" crate.

%files       -n %{name}+raw-api-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages
which use "serde" feature of "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Jun 06 2020 Josh Stone <jistone@redhat.com> - 3.11.4-1
- Update to 3.11.4

* Tue May 26 2020 Josh Stone <jistone@redhat.com> - 3.11.2-1
- Update to 3.11.2

* Sun Apr 19 11:55:54 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 3.11.1-1
- Update to 3.11.1

* Thu Apr 09 2020 Josh Stone <jistone@redhat.com> - 3.11.0-1
- Update to 3.11.0

* Wed Apr 08 2020 Josh Stone <jistone@redhat.com> - 3.10.0-1
- Update to 3.10.0

* Wed Apr 01 2020 Josh Stone <jistone@redhat.com> - 3.9.1-1
- Update to 3.9.1

* Sat Mar 21 17:22:43 CET 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 3.7.0-1
- Initial package
