# Generated by rust2rpm 15
%bcond_without check
%global debug_package %{nil}

%global crate prometheus

Name:           rust-%{crate}
Version:        0.10.0
Release:        1%{?dist}
Summary:        Prometheus instrumentation library for Rust applications

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            https://crates.io/crates/prometheus
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Prometheus instrumentation library for Rust applications.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+gen-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gen-devel %{_description}

This package contains library source intended for building other packages
which use "gen" feature of "%{crate}" crate.

%files       -n %{name}+gen-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+libc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libc-devel %{_description}

This package contains library source intended for building other packages
which use "libc" feature of "%{crate}" crate.

%files       -n %{name}+libc-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+nightly-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nightly-devel %{_description}

This package contains library source intended for building other packages
which use "nightly" feature of "%{crate}" crate.

%files       -n %{name}+nightly-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+process-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+process-devel %{_description}

This package contains library source intended for building other packages
which use "process" feature of "%{crate}" crate.

%files       -n %{name}+process-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+procfs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+procfs-devel %{_description}

This package contains library source intended for building other packages
which use "procfs" feature of "%{crate}" crate.

%files       -n %{name}+procfs-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+protobuf-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+protobuf-devel %{_description}

This package contains library source intended for building other packages
which use "protobuf" feature of "%{crate}" crate.

%files       -n %{name}+protobuf-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+protobuf-codegen-pure-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+protobuf-codegen-pure-devel %{_description}

This package contains library source intended for building other packages
which use "protobuf-codegen-pure" feature of "%{crate}" crate.

%files       -n %{name}+protobuf-codegen-pure-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+push-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+push-devel %{_description}

This package contains library source intended for building other packages
which use "push" feature of "%{crate}" crate.

%files       -n %{name}+push-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+reqwest-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+reqwest-devel %{_description}

This package contains library source intended for building other packages
which use "reqwest" feature of "%{crate}" crate.

%files       -n %{name}+reqwest-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Wed Sep 30 2020 Dusty Mabe <dusty@dustymabe.com> - 0.10.0-1
- Update to 0.10.0

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.9.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Sun May 17 2020 Robert Fairley <rfairley@redhat.com> - 0.9.0-1
- Update to 0.9.0

* Mon Mar 02 17:12:47 CET 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.8.0-1
- Update to 0.8.0

* Thu Feb 20 17:42:10 CET 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.7.0-4
- Update reqwest/hyper

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.7.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.7.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Thu Jun 20 11:09:00 UTC 2019 Robert Fairley <rfairley@redhat.com> - 0.7.0-1
- Update to 0.7.0 (RHBZ#1722428)

* Tue Jun 18 03:41:45 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.6.1-3
- Regenerate

* Mon Jun 17 10:50:00 UTC 2019 Robert Fairley <rfairley@redhat.com> - 0.6.1-2
- Update to hyper 0.12 (https://github.com/pingcap/rust-prometheus/pull/249)

* Mon Jun 10 19:00:25 UTC 2019 Robert Fairley <rfairley@redhat.com> - 0.6.1-1
- Initial package (#1717614)
