# Generated by rust2rpm 12
# * Some mismatch on stable Rust, https://github.com/servo/rustc-test/issues/7
%bcond_with check
%global debug_package %{nil}

%global crate rustc-test

Name:           rust-%{crate}
Version:        0.3.0
Release:        8%{?dist}
Summary:        Fork of Rust’s `test` crate that doesn’t require unstable language features

# Upstream license specification: MIT OR Apache-2.0
# https://github.com/servo/rustc-test/issues/5
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/rustc-test
Source:         %{crates_source}
# Initial patched metadata
# * Bump term to 0.6, https://github.com/servo/rustc-test/pull/9
Patch0:         rustc-test-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Fork of Rust’s `test` crate that doesn’t require unstable language features.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+asm_black_box-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+asm_black_box-devel %{_description}

This package contains library source intended for building other packages
which use "asm_black_box" feature of "%{crate}" crate.

%files       -n %{name}+asm_black_box-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+capture-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+capture-devel %{_description}

This package contains library source intended for building other packages
which use "capture" feature of "%{crate}" crate.

%files       -n %{name}+capture-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.3.0-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Sat Dec 14 03:22:45 CET 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.3.0-7
- Bump term to 0.6

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.3.0-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sun Feb 17 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.0-5
- Adapt to new packaging

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.3.0-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Sat Jul 14 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.3.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Thu May 10 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.0-2
- Bump term to 0.5

* Tue Mar 13 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.0-1
- Update to 0.3.0

* Fri Feb 09 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Mon Jan 08 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.0-2
- Rebuild for rust-packaging v5

* Wed Jul 05 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.2.0-1
- Initial package
