# Generated by rust2rpm 13
# * dependency on smithay-client-toolkit is too old
%bcond_with check
%global debug_package %{nil}

%global crate andrew

Name:           rust-%{crate}
Version:        0.3.0
Release:        1%{?dist}
Summary:        Convenient drawing of shapes, lines and text to buffers

# Upstream license specification: MIT
License:        MIT
URL:            https://crates.io/crates/andrew
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Andrew crate provides convenient drawing of objects such as shapes, lines and
text to buffers.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md CHANGELOG.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Oct 04 2020 Fabio Valentini <decathorpe@gmail.com> - 0.3.0-1
- Initial package
