# Generated by rust2rpm 15
# * Tests require internet and a token
%bcond_with check
%global debug_package %{nil}

%global crate news-flash

Name:           rust-%{crate}
Version:        1.0.3
Release:        1%{?dist}
Summary:        Base library for a modern feed reader

# Upstream license specification: GPL-3.0-or-later
License:        GPLv3+
URL:            https://crates.io/crates/news-flash
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Base library for a modern feed reader.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+readability-fallback-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+readability-fallback-devel %{_description}

This package contains library source intended for building other packages
which use "readability-fallback" feature of "%{crate}" crate.

%files       -n %{name}+readability-fallback-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+readability-fork-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+readability-fork-devel %{_description}

This package contains library source intended for building other packages
which use "readability-fork" feature of "%{crate}" crate.

%files       -n %{name}+readability-fork-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Jun 21 17:45:57 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 1.0.3-1
- Update to 1.0.3

* Sun Jun 07 12:16:36 CEST 2020 Igor Raits <i.gnatenko.brain@gmail.com> - 1.0.2-1
- Initial package
