# Generated by rust2rpm 13
%bcond_without check
%global debug_package %{nil}

%global crate glutin_egl_sys

Name:           rust-%{crate}
Version:        0.1.5
Release:        1%{?dist}
Summary:        Egl bindings for glutin

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            https://crates.io/crates/glutin_egl_sys
Source:         %{crates_source}
# Initial patched metadata
# Remove Windows target
Patch0:         glutin_egl_sys-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Egl bindings for glutin.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Aug 22 17:40:00 CEST 2020 returntrip <stefano@figura.im> - 0.1.5-1
- Upate to version 1.0.5

* Sat Aug 01 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.4-3
- Second attempt - Rebuilt for
  https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.4-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Tue Jun 23 16:17:10 CEST 2020 returntrip <stefano@figura.im> - 0.1.4-1
- Initial package
