# Generated by rust2rpm 13
%bcond_with check
%global debug_package %{nil}

%global crate picky-asn1-der

Name:           rust-%{crate}
Version:        0.2.4
Release:        1%{?dist}
Summary:        ASN.1-DER subset for serde

# Upstream license specification: MIT OR Apache-2.0
# https://github.com/Devolutions/picky-rs/issues/56
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/picky-asn1-der
Source:         %{crates_source}
# Initial patched metadata
Patch0:         picky-asn1-der-fix-metadata.diff

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
ASN.1-DER subset for serde.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+debug_log-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debug_log-devel %{_description}

This package contains library source intended for building other packages
which use "debug_log" feature of "%{crate}" crate.

%files       -n %{name}+debug_log-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+lazy_static-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+lazy_static-devel %{_description}

This package contains library source intended for building other packages
which use "lazy_static" feature of "%{crate}" crate.

%files       -n %{name}+lazy_static-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Wed Sep 16 2020 Peter Robinson <pbrobinson@fedoraproject.org> 0.2.4-1

* Fri Sep 11 2020 Peter Robinson <pbrobinson@fedoraproject.org> 0.2.2-1
- Initial package
