# Generated by rust2rpm 13
%bcond_without check

%global crate cargo-readme

Name:           rust-%{crate}
Version:        3.2.0
Release:        2%{?dist}
Summary:        Cargo subcommand to generate README.md content from doc comments

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/cargo-readme
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Cargo subcommand to generate README.md content from doc comments.}

%description %{_description}

%if ! %{__cargo_skip_build}
%package     -n %{crate}
Summary:        %{summary}
# Apache-2.0 OR BSL-1.0 (1): ryu
# Apache-2.0 OR MIT (32): environment, backtrace, lazy_static, syn, cc, percent-encoding, rustc-demangle, proc-macro2, unicode-width, libc, regex, vec_map, failure_derive, bitflags, failure, winapi, thread_local, unicode-xid, serde_json, cfg-if, backtrace-sys, serde_derive, itoa, quote, hermit-abi, toml, winapi-x86_64-pc-windows-gnu, assert_cli, winapi-i686-pc-windows-gnu, cargo-readme, serde, regex-syntax
# MIT (7): ansi_term, clap, difference, atty, strsim, synstructure, textwrap
# MIT OR Unlicense (2): memchr, aho-corasick
# MPL-2.0 (1): colored
License:        MIT and ASL 2.0 and zlib and MPLv2.0

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE-APACHE LICENSE-MIT
%doc README.md
%{_bindir}/cargo-readme
%endif

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test -- -- --skip    alternate_input_a_little_bit_longer \
                            alternate_input_empty_docs \
                            alternate_input_single_line \
                            alternate_template \
                            append_license \
                            no_append_license \
                            badges \
                            default_behavior \
                            entrypoint_resolution_lib \
                            entrypoint_resolution_main \
                            entrypoint_resolution_cargo_bin \
                            entrypoint_resolution_cargo_lib \
                            multiline_doc \
                            multiple_bin_fail \
                            no_entrypoint_fail \
                            no_template \
                            template_with_version
%endif

%changelog
* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 3.2.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Thu Jul 02 14:57:27 EEST 2020 Artem Polishchuk <ego.cordatus@gmail.com> - 3.2.0-1
- Initial package
