# Generated by rust2rpm 15
%bcond_without check
%global debug_package %{nil}

%global crate trybuild

Name:           rust-%{crate}
Version:        1.0.35
Release:        1%{?dist}
Summary:        Test harness for ui tests of compiler diagnostics

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/trybuild
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Test harness for ui tests of compiler diagnostics.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-MIT
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+diff-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+diff-devel %{_description}

This package contains library source intended for building other packages
which use "diff" feature of "%{crate}" crate.

%files       -n %{name}+diff-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%package     -n %{name}+dissimilar-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dissimilar-devel %{_description}

This package contains library source intended for building other packages
which use "dissimilar" feature of "%{crate}" crate.

%files       -n %{name}+dissimilar-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -a

%build
%cargo_build -a

%install
%cargo_install

%if %{with check}
%check
%cargo_test -a
%endif

%changelog
* Wed Sep 16 2020 Fabio Valentini <decathorpe@gmail.com> - 1.0.35-1
- Update to 1.0.35.

* Wed Aug 26 2020 Josh Stone <jistone@redhat.com> - 1.0.33-1
- Update to 1.0.33

* Thu Aug 20 2020 Josh Stone <jistone@redhat.com> - 1.0.32-1
- Update to 1.0.32

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.30-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Fri Jun 19 2020 Josh Stone <jistone@redhat.com> - 1.0.30-1
- Update to 1.0.30

* Mon Jun 01 13:57:40 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 1.0.28-1
- Update to 1.0.28

* Fri May 08 2020 Josh Stone <jistone@redhat.com> - 1.0.27-1
- Update to 1.0.27

* Wed Apr 29 2020 Josh Stone <jistone@redhat.com> - 1.0.26-1
- Update to 1.0.26

* Wed Apr 08 2020 Josh Stone <jistone@redhat.com> - 1.0.25-1
- Update to 1.0.25

* Tue Mar 10 2020 Josh Stone <jistone@redhat.com> - 1.0.24-1
- Update to 1.0.24

* Fri Feb 21 2020 Josh Stone <jistone@redhat.com> - 1.0.23-1
- Update to 1.0.23

* Thu Feb 20 2020 Josh Stone <jistone@redhat.com> - 1.0.22-1
- Update to 1.0.22

* Mon Feb 10 2020 Josh Stone <jistone@redhat.com> - 1.0.21-1
- Update to 1.0.21

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.18-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Fri Dec 13 21:37:19 CET 2019 Robert-André Mauchin <zebob.m@gmail.com> - 1.0.18-1
- Initial package
