# Generated by go2rpm 1
%bcond_without check

# https://github.com/eth0izzle/shhgit
%global goipath         github.com/eth0izzle/shhgit
Version:                0.2

%gometa

%global common_description %{expand:
Find GitHub secrets in real time.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           shhgit
Release:        2%{?dist}
Summary:        GitHub secrets search tool

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/fatih/color)
BuildRequires:  golang(github.com/google/go-github/github)
BuildRequires:  golang(golang.org/x/oauth2)
BuildRequires:  golang(gopkg.in/src-d/go-git.v4)
BuildRequires:  golang(gopkg.in/yaml.v3)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/shhgit %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Wed May 27 2020 Fabian Affolter <mail@fabian-affolter.ch> - 0.2-1
- Initial package
